### ISSUE TITLE
What are the formulas for upgrade benefits and cost? 

### ISSUE THREAD

**Issue by dantogno** [aablanco01/TowerDefense#21]
I recommend a google spreadsheet that contains the equations and then a series of rows for each upgrade level. If you add a new upgrade row, the values are automatically generated, because they are governed by a formula. If you change a value in the formula, it changes every cell.

You would have to manually copy the formulas to your game code, but a google sheet will make it easy for me to review what you are doing.

**Comment by aablanco01** [comment]
Upgrades can be viewed within the Directed Study folder I've created and shared with you! Here's a direct link for your convince.

https://drive.google.com/open?id=1WlNal-Lhlw_v5J2TRLrDPGFi-nOskyS2FbD5PP0pz8M
