### ISSUE TITLE
"accurate shots increases the amount of gold you earn per kill."

### ISSUE THREAD

**Issue by dantogno** [aablanco01/TowerDefense#35]
What are the specific rules? How are you judging accuracy?

**Comment by dantogno** [comment]
OK, I think I'm starting to get it from playing. But let me know if I'm wrong! 

It's like a multiplier that goes up the more hits I land, but goes away if I miss or don't shoot anything in some set amount of time? If so, that time limit should be indicated in the UI element that is tracking my bonus gold. A meter decreasing is better than a number here.

Here's an example (bottom left clock / combo UI): https://youtu.be/L5nURi-lyAk

**Comment by aablanco01** [comment]
You got the exact idea! I'll fix the description to that to help the player understand the rules better, but that's how it's going to work!
